version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: talabash-php-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: nginx-web
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: mariadb-db
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: talabash
      MYSQL_DATABASE: talabash
      MYSQL_USER: talabash
      MYSQL_PASSWORD: talabash
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - app-network

networks:
  app-network:
